version: 2
build:
  os: ubuntu-20.04
sphinx:
  configuration: docs/conf.py
python:
  version: 3.8
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
submodules:
  include:
     - "docs/tutorials/notebooks"
  recursive: true
